baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Schedule I Modding Wiki'

[module]
    [[module.imports]]
        path = "github.com/colinwilson/lotusdocs"
        disable = false
    [[module.imports]]
        path = "github.com/gohugoio/hugo-mod-bootstrap-scss/v5"
        disable = false

[params.docs]
themeColor = "green"
darkMode = true
sidebarIcons = true
lastMod = true


[caches]
  [caches.images]
    dir = ':cacheDir/images'
